service: quiztopia-api
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  stage: dev

  httpApi:
    payload: '2.0'

  environment:
    TABLE_NAME: quiztopia-${sls:stage}-v1
    JWT_SECRET: ${ssm:/quiztopia/${sls:stage}/JWT_SECRET, env:JWT_SECRET, 'CHANGE_ME_DEV_SECRET'}

  # Global IAM-policy (Serverless skapar rätt Lambda-trust-policy åt oss)
  iam:
    role:
      statements:
        # DynamoDB (tabell + GSI)
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:BatchWriteItem
            - dynamodb:Query
          Resource:
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/quiztopia-${sls:stage}-v1
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/quiztopia-${sls:stage}-v1/index/*
        # CloudWatch Logs (basic exec)
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "*"

build:
  esbuild:
    bundle: true
    platform: node
    target: node20
    minify: true
    sourcemap: true
    sourcesContent: false
    external:
      - jsonwebtoken



package:
  individually: true
  patterns:
    - '!**/*.test.*'
    - '!tests/**'
    - '!*.md'
    - '!**/*.md'
    - '!node_modules/.bin/**'

custom:
  tableName: quiztopia-${sls:stage}-v1

functions:
  ping:
    handler: src/functions/ping.handler
    events:
      - httpApi:
          method: GET
          path: /health

  authRegister:
    handler: src/functions/auth/register.handler
    events:
      - httpApi:
          method: POST
          path: /auth/register

  authLogin:
    handler: src/functions/auth/login.handler
    events:
      - httpApi:
          method: POST
          path: /auth/login

  getQuizzes:
    handler: src/functions/quizzes/list.handler
    events:
      - httpApi:
          method: GET
          path: /quizzes

  getQuizById:
    handler: src/functions/quizzes/get.handler
    events:
      - httpApi:
          method: GET
          path: /quizzes/{quizId}

  createQuiz:
    handler: src/functions/quizzes/create.handler
    events:
      - httpApi:
          method: POST
          path: /quizzes

  deleteQuiz:
    handler: src/functions/quizzes/delete.handler
    events:
      - httpApi:
          method: DELETE
          path: /quizzes/{quizId}

  addQuestion:
    handler: src/functions/questions/create.handler
    events:
      - httpApi:
          method: POST
          path: /quizzes/{quizId}/questions

  submitScore:
    handler: src/functions/scores/submit.handler
    events:
      - httpApi:
          method: POST
          path: /quizzes/{quizId}/scores

  getLeaderboard:
    handler: src/functions/scores/leaderboard.handler
    events:
      - httpApi:
          method: GET
          path: /quizzes/{quizId}/leaderboard

resources:
  Resources:
    QuiztopiaTableV1:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      UpdateReplacePolicy: Retain
      Properties:
        TableName: ${self:custom.tableName}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
          - AttributeName: GSI1PK
            AttributeType: S
          - AttributeName: GSI1SK
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: GSI1
            KeySchema:
              - AttributeName: GSI1PK
                KeyType: HASH
              - AttributeName: GSI1SK
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
